{% set name = "OpenFBX" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/nem0/OpenFBX/archive/ef492927cefc16ad8733ec08bcc8df5434dbb1ae.tar.gz
    sha256: 233f5971f6d0ec56a25631f6a9ef39875cc88f5c0d5a7ff7e32e34f219a724a5

build:
  number: 4
  run_exports:
    - {{ pin_subpackage('openfbx', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not win]
  host:
    - libdeflate

test:
  commands:
    - test -f $PREFIX/share/openfbx/openfbxConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\share\\openfbx\\openfbxConfig.cmake exit 1  # [win]

about:
  home: https://github.com/nem0/OpenFBX
  summary: 'Lightweight open source FBX importer'
  description: |
    Lightweight open source FBX importer. Used in Lumix Engine and Flax Engine. It's an almost
    full-featured importer. It can load geometry (with uvs, normals, tangents, colors), skeletons,
    animations, blend shapes, materials, textures, cameras and lights.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/nem0/OpenFBX

extra:
  recipe-maintainers:
    - jeongseok-meta
